### ISSUE TITLE
Clarification on the Definition of Task Function in KGQA

### ISSUE THREAD

**Issue by YurainSoon** [lanjiuqing64/KGdata#3]
Hi.

First of all, thank you for your work on this paper. I have a question regarding the task definition in the KGQA problem.

In the paper, you define the task as:

$$T:(q, E), G \rightarrow Y$$

However, it is unclear to me where exactly the set $$E$$ originates from. For instance, when using the WebQSP dataset, is $$E$$ initialized as the TopicEntity? 

Could you kindly clarify this for me?

Thank you in advance for your time!

**Comment by lanjiuqing64** [comment]
Hi,

Thank you for your question and for your interest in our work!

You're absolutely right. In the case of the WebQSP dataset, the set E is indeed initialized as the TopicEntity. 

I hope this clarifies your question! Please feel free to reach out if you have any further doubts.
